export type Project = {
  id: 1;
  name: number;
  description: string;
  initialDate: string;
  dueData: string;
  status: string;
  imgUrl: string;
  budget: number;
  expenses: number;
  invoicing: number;
  owner: number;
  client: number;
  clientName: number;
  categoryId: number;
  categoryDescription: string;
  percentCompleted: number;
  totalTasks: number;
  unfinishedTasks: number;
  completedTasks: number;
  canceledTasks: number;
};
